version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
      - image: circleci/mongo:3.6.12
      - image: circleci/redis:5.0.4
    steps:
      - checkout
#      - run:
#          name: Upgrade Yarn
#          command: sudo npm i -g yarn@$(node -p 'require("./package.json").engines.yarn')
#      - restore_cache:
#          name: Restore Yarn cache
#          keys:
#            - yarn-packages-{{ checksum "yarn.lock" }}
#      - run:
#          name: Install Dependencies
#          command: yarn
#      - save_cache:
#          name: Save Yarn Package cache
#          key: yarn-packages-{{ checksum "yarn.lock" }}
#          paths:
#            - ~/.cache/yarn
#      - run:
#          name: Run tests
#          command: yarn test:ci
      # Don't try building connectors if not in branch master or develop
      - run:
          name: Check branch
          command: |
            if [ "$CIRCLE_BRANCH" != "develop" ] && [ "$CIRCLE_BRANCH" != "master" ] && [ "$CIRCLE_BRANCH" != "feature/docker-single" ]; then
              circleci-agent step halt
              echo "Skipping build, current branch not master or develop"
            fi
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              tag="production"
            else
              tag="staging"
            fi
            echo "export CONNECTORS_TAG=${tag}" >> $BASH_ENV
      - setup_remote_docker
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build connectors
          command: |
            docker build . -t hull/hull-connectors:$CONNECTORS_TAG
      - run:
          name: Deploy connectors
          command: |
            docker push hull/hull-connectors:$CONNECTORS_TAG
